name: Portfolio Jest Test

on:
  push:
    branches:
      - "**"
    paths:
      - "portfolio/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "portfolio/**"

permissions:
  checks: write
  contents: write

jobs:
  Linter:
    name: Run Portfolio Jest Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"
          check-latest: true

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Jest
        run: npm run jest-test
