name: Portfolio Linter

on:
  push:
    branches:
      - "**"
    paths:
      - "portfolio/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "portfolio/**"

permissions:
  checks: write
  contents: write

jobs:
  Linter:
    name: Run Portfolio Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "latest"

      - name: Install Node.js dependencies
        run: npm install

      - name: Run ESLinter
        run: ng lint --fix
